spring:
  application:
    name: pure-grpc
microservice-base:
  grpc:
    client:
      enabled: true
      channels:
        hello: localhost:9090
    server:
      debug-enabled: true
      port: 9090