spring:
  application:
    name: rpc-feign
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  metrics:
    tags:
      application: ${spring.application.name}
#username: real